sudo: required
services:
  - docker

before_install:
  - docker build -t testep02/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run testep02/react-test npm test -- --coverage

after_success:
  - docker build -t testep02/multi-client ./client
  - docker build -t testep02/multi-nginx ./nginx
  - docker build -t testep02/multi-server ./server
  - docker build -t testep02/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push testep02/multi-client
  - docker push testep02/multi-nginx
  - docker push testep02/multi-server
  - docker push testep02/multi-worker
